apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: filestore-shared # ✅ Points to the SC created
  resources:
    requests:
      storage: 1Ti # Note: Filestore "Standard" often requires a 1Ti minimum
