apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: ecommerce
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword

