apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80         # The port users will hit in their browser
      targetPort: 80   # The port Nginx is listening on inside the container
