apiVersion: v1
kind: Service
metadata:
  name: multi-tier-app-prod 
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend
    version: v1 # ⬅️ CURRENTLY POINTING TO BLUE
