apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-tier-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Abhi4004/kubernetes-practical-workflows.git
    targetRevision: v1.0-final-submission
    path: task-2-Multi-Tier-App/environments/dev
    directory:
      recurse: true 
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
